tap "anomalyco/tap", "https://github.com/anomalyco/homebrew-tap.git"
tap "getsentry/tools"
tap "gromgit/fuse"
tap "guitaripod/songlink-cli"
tap "guitaripod/tap", "https://github.com/guitaripod/homebrew-tap.git"
tap "oven-sh/bun", trusted: true
tap "skiptools/skip"
tap "supabase/tap"
tap "xcodesorg/made"
brew "aria2"
brew "btop"
brew "cliclick"
brew "cmake"
brew "deno"
brew "docker", link: false
brew "docker-compose"
brew "lua"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "gh"
brew "git-filter-repo"
brew "git-lfs"
brew "gitui"
brew "go"
brew "gradle"
brew "gtk4"
brew "handbrake"
brew "imagemagick"
brew "iperf3"
brew "lazydocker"
brew "libadwaita"
brew "libimobiledevice"
brew "mas"
brew "yt-dlp"
brew "mpv", link: false
brew "ncdu"
brew "tree-sitter"
brew "neovim"
brew "node"
brew "ollama", restart_service: :changed
brew "opencode"
brew "p7zip"
brew "pipx"
brew "pkgconf"
brew "poppler"
brew "pyright"
brew "python@3.12"
brew "render"
brew "rsync"
brew "ruby", link: false
brew "rust-analyzer"
brew "sentry-cli"
brew "supabase"
brew "tesseract"
brew "tmux"
brew "tokei"
brew "tree"
brew "tree-sitter-cli"
brew "xcbeautify"
brew "xclogparser"
brew "xcode-build-server"
brew "xcodegen"
brew "xcodes"
brew "guitaripod/songlink-cli/songlink-cli", trusted: true
brew "oven-sh/bun/bun"
cask "1password"
cask "android-commandlinetools"
cask "android-platform-tools"
cask "android-studio"
cask "appcleaner"
cask "balenaetcher"
cask "cleanshot"
cask "coconutbattery"
cask "discord"
cask "docker-desktop"
cask "flux-app"
cask "font-fira-code-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "gitup-app"
cask "handbrake-app"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "linearmouse"
cask "meetingbar"
cask "notunes"
cask "obs"
cask "pcsx2"
cask "raycast"
cask "rectangle"
cask "steam"
cask "stolendata-mpv"
cask "telegram"
cask "vivaldi"
mas "Blackmagic Disk Speed Test", id: 425264550
mas "Xcode", id: 497799835
cargo "emusync"
cargo "unrager"
cargo "worker-build"
npm "@redocly/cli"
npm "@vue/cli"
npm "aicommits"
npm "playwright"
npm "wrangler"
